// Authenticated downloads keep shared files private; no public or signed URLs.
export const CHAT_BUCKET='sks-chat';
export const MAX_FILE_SIZE=20*1024*1024;
const types={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif',pdf:'application/pdf',txt:'text/plain',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',ppt:'application/vnd.ms-powerpoint',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation'};
export function validateChatFiles(files){if(files.length>5)throw Error('En fazla 5 dosya seçebilirsiniz.');return files.map(f=>{const ext=f.name.split('.').pop().toLowerCase(),mime=types[ext];if(!mime)throw Error('Desteklenen dosyalar: JPG, PNG, WEBP, GIF, PDF, TXT, Word, Excel ve PowerPoint.');if(f.size<1||f.size>MAX_FILE_SIZE)throw Error('Her dosya 20 MB veya daha küçük olmalıdır.');return {file:f,ext,mime};});}
export function createTeamChat(client,getContext,notify,onUnread,onOpenTask){
 const cache=new Map(),urls=new Map();let timer,subscription,viewerId=null,active='team',homeChannel='team',people=[],peopleSearch='',unread=[],sending=false,epoch=0;
 const ctx=()=>getContext();
 const bytes=n=>n<1024*1024?Math.ceil(n/1024)+' KB':(n/1024/1024).toFixed(1)+' MB';

 function directChannel(a,b){return 'dm:'+ [a,b].sort().join(':');}
 function directPeer(channel){return people.find(p=>p.user_id&&channel.split(':').includes(p.user_id)&&p.user_id!==ctx().user?.id);}
 function peopleList(){const {e,user}=ctx(),term=peopleSearch.toLocaleLowerCase('tr');const count=c=>Number(unread.find(x=>x.channel===c)?.count??0);return `<button type="button" class="chat-person ${homeChannel==='team'?'selected':''}" data-chat-action="select-group"><span class="chat-person-avatar group-avatar">#</span><span><strong>Ortak ekip grubu</strong><small>Dijital Kanallar Birimi · Herkes</small></span>${count('team')?`<b>${count('team')}</b>`:''}</button><p class="chat-list-caption">BİREBİR MESAJLAR</p>${people.filter(p=>p.user_id!==user.id&&p.name.toLocaleLowerCase('tr').includes(term)).map(p=>{const c=p.user_id?directChannel(user.id,p.user_id):'',n=count(c);return `<button type="button" class="chat-person ${homeChannel===c?'selected':''}" data-chat-action="select-person" data-user="${e(p.user_id??'')}" ${!p.user_id?'disabled':''}><span class="chat-person-avatar">${e(p.name.slice(0,1))}</span><span><strong>${e(p.name)}</strong><small>${p.user_id?(p.role==='manager'?'Birim sorumlusu':'Öğrenci'):p.active?'Hesap oluşturması bekleniyor':'Henüz aktif değil'}</small></span>${n?`<b>${n}</b>`:''}</button>`;}).join('')||'<p class="chat-people-empty">Kullanıcı bulunamadı.</p>'}`;}
 function updatePeople(){const list=document.querySelector('.chat-people-list');if(list)list.innerHTML=peopleList();}
 async function loadPeople(){if(!viewerId)return;const token=epoch;const {data,error}=await client.rpc('sks_chat_people');if(token!==epoch)return;if(error){notify(error.message,true);return;}people=Array.isArray(data)?data:[];updatePeople();}
 function home(){return `<div class="chat-workspace"><aside class="chat-people"><div class="chat-people-heading"><h2>Konuşmalar</h2><p>Ortak grup ve kişisel mesajlar</p><input type="search" class="chat-people-search" aria-label="Kullanıcı ara" placeholder="Kullanıcı ara…" value="${ctx().e(peopleSearch)}"></div><nav class="chat-people-list" aria-label="Sohbet seçimi">${peopleList()}</nav><p class="chat-people-help">Birebir mesajlara yalnızca konuşmadaki iki kişi erişebilir.</p></aside><div class="chat-conversations"><div data-chat-frame="${ctx().e(homeChannel)}">${view(homeChannel)}</div></div></div>`;}
 function selectConversation(channel){if(sending)return;homeChannel=channel;active=channel;const container=document.querySelector('.chat-conversations');if(!container)return;let target=[...container.children].find(x=>x.dataset.chatFrame===channel);for(const node of container.children)node.hidden=node!==target;if(!target){target=document.createElement('div');target.dataset.chatFrame=channel;target.innerHTML=view(channel);container.append(target);bind(target);}else{target.hidden=false;void sync(channel);}updatePeople();target.querySelector('textarea')?.focus();}
 function channelNotices(){const {e,state}=ctx();return unread.filter(x=>x.channel!=='team').map(x=>{const t=state.tasks.find(t=>'task:'+t.id===x.channel);return t?`<button type="button" data-chat-action="task" data-id="${t.id}">${e(t.title)} <b>${Number(x.count)} yeni mesaj</b></button>`:'';}).join('');}
 function rows(channel){const {e,name,state,user}=ctx(),data=cache.get(channel);if(!data)return '<div class="chat-empty">Mesajlar yükleniyor…</div>';if(data.error)return '<div class="chat-empty" role="alert">'+e(data.error)+'</div>';return data.messages.map(m=>`<article class="chat-message ${m.author_id===user.id?'chat-own':''}" data-message="${m.id}"><div class="chat-message-head"><span class="chat-avatar">${e(m.author.slice(0,1))}</span><strong>${e(m.author)}</strong><time datetime="${e(m.created)}">${new Date(m.created).toLocaleString('tr-TR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time>${state.viewer.manager||m.author_id===user.id?`<button type="button" class="chat-remove" data-chat-action="remove" data-id="${m.id}" aria-label="Mesajı ve eklerini herkesten sil">Herkesten sil</button>`:''}</div>${m.body?`<p class="chat-body">${e(m.body)}</p>`:''}${m.mentions?.length?`<div class="chat-mentions">${m.mentions.map(id=>`<span>@${e(name(id))}</span>`).join('')}</div>`:''}${m.files?.length?`<div class="chat-files">${m.files.map(f=>`<button type="button" class="chat-file" data-chat-action="download" data-file="${f.id}"><span>${f.mime.startsWith('image/')?`<img data-chat-image="${f.id}" alt="${e(f.name)}" loading="lazy">`:'<span class="chat-file-icon">▤</span>'}</span><span><strong>${e(f.name)}</strong><small>${bytes(f.size)} · İndir</small></span></button>`).join('')}</div>`:''}</article>`).join('')||'<div class="chat-empty"><strong>Konuşmayı başlatın.</strong><span>Bir mesaj yazın veya çalışma dosyası paylaşın.</span></div>';}
 function view(channel){const {e,name,state}=ctx();return `<section class="chat-panel" data-chat-channel="${e(channel)}"><header class="chat-header"><div><span class="eyebrow">EKİP İLETİŞİMİ</span><h2>${channel==='team'?'Ortak ekip grubu':channel.startsWith('dm:')?e(directPeer(channel)?.name??'Birebir mesaj'):'Görev konuşması'}</h2><p>${channel==='team'?'Ekibinizle konuşun, görsel ve belgeleri paylaşın.':channel.startsWith('dm:')?'Bu konuşmayı yalnızca siz ve karşınızdaki kişi görebilirsiniz.':'Bu görevdeki sorumlu, destek ekibi ve birim sorumlusu erişebilir.'}</p></div><span class="chat-private">● Özel alan</span></header><div class="chat-channel-notices">${channel==='team'?channelNotices():''}</div><div class="chat-history"><button type="button" class="text-button" data-chat-action="older">Önceki mesajları yükle</button><button type="button" class="text-button" data-chat-action="refresh">Yenile</button></div><div class="chat-log" role="log" aria-label="Sohbet mesajları" aria-live="polite">${rows(channel)}</div><form class="chat-compose"><label class="sr-only" for="chat-body-${channel.replace(':','-')}">Mesajınız</label><textarea id="chat-body-${channel.replace(':','-')}" name="body" rows="3" maxlength="5000" placeholder="Mesajınızı yazın…"></textarea><div class="chat-picked" aria-live="polite"></div><div class="chat-compose-actions"><label class="chat-attach">＋ Dosya ekle<input type="file" name="files" multiple accept="${Object.keys(types).map(x=>'.'+x).join(',')}" class="sr-only"></label>${!channel.startsWith('dm:')?`<details class="chat-tag"><summary>@ Öğrenci etiketle</summary><div>${state.members.filter(m=>m.active).map(m=>`<label><input type="checkbox" name="mentions" value="${m.id}">${e(name(m.id))}</label>`).join('')}</div></details>`:''}<button class="primary" type="submit">Gönder</button></div><div class="chat-compose-footer"><small>En fazla 5 dosya · Dosya başına 20 MB</small><span class="chat-send-status" role="status"></span></div></form></section>`;}
 function panel(channel){return [...document.querySelectorAll('[data-chat-channel]')].find(p=>p.dataset.chatChannel===channel&&!p.closest('[hidden]')&&(!p.closest('dialog')||p.closest('dialog').open));}
 function fileById(id){for(const d of cache.values())for(const m of d.messages??[]){const f=m.files?.find(x=>x.id===id);if(f)return f;}return null;}
 async function loadBlob(f){if(urls.has(f.path))return urls.get(f.path);const token=epoch,{data,error}=await client.storage.from(CHAT_BUCKET).download(f.path);if(error)throw error;if(token!==epoch)throw Error('Oturum değişti.');const url=URL.createObjectURL(data);urls.set(f.path,url);return url;}
 async function previews(channel){const p=panel(channel);if(!p)return;for(const img of p.querySelectorAll('[data-chat-image]')){const f=fileById(Number(img.dataset.chatImage));if(!f||!/^image\/(jpeg|png|webp|gif)$/.test(f.mime))continue;try{const u=await loadBlob(f);if(img.isConnected)img.src=u;}catch{if(img.isConnected){img.alt='Görsel açılamadı';img.classList.add('preview-failed');}}}}
 function revokeUnused(){const paths=new Set([...cache.values()].flatMap(d=>(d.messages??[]).flatMap(m=>(m.files??[]).map(f=>f.path))));for(const [p,u]of urls)if(!paths.has(p)){URL.revokeObjectURL(u);urls.delete(p);}}
 async function sync(channel=active,older=false){if(!viewerId)return;const request=(cache.get(channel)?.request??0)+1;cache.set(channel,{...(cache.get(channel)??{}),request});const token=epoch,p=panel(channel),log=p?.querySelector('.chat-log'),nearBottom=!log||log.scrollHeight-log.scrollTop-log.clientHeight<100,old=cache.get(channel),before=older?old?.messages?.[0]?.id:null;if(older&&!before)return;
 const {data,error}=await client.rpc('sks_chat',{p_channel:channel,p_before:before});if(token!==epoch||cache.get(channel)?.request!==request)return;
 if(error){cache.set(channel,{messages:[],error:error.message});if(log)log.innerHTML=rows(channel);revokeUnused();return;}
 if(!older&&old?.messages?.length>50){const oldest=old.messages[0].id;let last=data.messages[0]?.id;while(last&&last>oldest&&data.messages.length<500){const page=await client.rpc('sks_chat',{p_channel:channel,p_before:last});if(token!==epoch)return;if(page.error||!page.data.messages.length)break;data.messages.unshift(...page.data.messages);last=page.data.messages[0].id;}}
 const merged=older?[...data.messages,...(old?.messages??[])]:[...(old?.messages??[]).filter(m=>m.id<(data.messages[0]?.id??0)),...data.messages];
 // Refresh the loaded history as well, so removed messages disappear from older pages.
 cache.set(channel,{request,messages:older?[...new Map(merged.map(m=>[m.id,m])).values()]:data.messages});unread=data.unread??[];onUnread(unread);updatePeople();const notices=panel('team')?.querySelector('.chat-channel-notices');if(notices)notices.innerHTML=channelNotices();
 if(log){const scroll=log.scrollTop,height=log.scrollHeight;log.innerHTML=rows(channel);if(older)log.scrollTop=scroll+log.scrollHeight-height;else if(nearBottom)log.scrollTop=log.scrollHeight;void previews(channel);if(document.visibilityState==='visible'){const last=cache.get(channel).messages.at(-1)?.id;if(last){const r=await client.rpc('sks_chat_read',{p_channel:channel,p_last:last});if(!r.error){unread=unread.filter(x=>x.channel!==channel);onUnread(unread);updatePeople();}}}}
 revokeUnused();}
 function bind(container=document){const search=container.querySelector('.chat-people-search');if(search)search.oninput=()=>{peopleSearch=search.value;updatePeople();};for(const p of container.querySelectorAll('[data-chat-channel]')){const channel=p.dataset.chatChannel;active=channel;const form=p.querySelector('.chat-compose'),input=form.elements.files;
 input.onchange=()=>{try{validateChatFiles([...input.files]);p.querySelector('.chat-picked').textContent=[...input.files].map(f=>f.name+' ('+bytes(f.size)+')').join(' · ');}catch(err){input.value='';p.querySelector('.chat-picked').textContent='';notify(err.message,true);}};
 form.onsubmit=async ev=>{ev.preventDefault();if(sending)return;let files;try{files=validateChatFiles([...input.files]);}catch(err){notify(err.message,true);return;}const body=form.elements.body.value.trim(),mentions=[...form.querySelectorAll('[name=mentions]:checked')].map(x=>Number(x.value));if(!body&&!files.length){notify('Mesaj yazın veya dosya seçin.',true);return;}sending=true;const controls=[...form.querySelectorAll('input,textarea,button')];controls.forEach(x=>x.disabled=true);const uploaded=[],status=p.querySelector('.chat-send-status');try{
 for(const item of files){status.textContent='Dosyalar yükleniyor…';const path=channel+'/'+ctx().user.id+'/'+crypto.randomUUID()+'.'+item.ext;const {error}=await client.storage.from(CHAT_BUCKET).upload(path,item.file,{contentType:item.mime,upsert:false});if(error)throw error;uploaded.push({path,name:item.file.name,mime:item.mime,size:item.file.size});}
 status.textContent='Gönderiliyor…';const {error}=await client.rpc('sks_chat_send',{p_channel:channel,p_body:body,p_files:uploaded,p_mentions:mentions});if(error)throw error;
 form.reset();p.querySelector('.chat-picked').textContent='';status.textContent='Gönderildi';await sync(channel);const log=p.querySelector('.chat-log');log.scrollTop=log.scrollHeight;
 }catch(err){if(uploaded.length){await client.storage.from(CHAT_BUCKET).remove(uploaded.map(f=>f.path));}status.textContent='Gönderilemedi; yeniden deneyebilirsiniz.';notify(err.message,true);}finally{sending=false;controls.forEach(x=>x.disabled=false);}};
 form.elements.body.onkeydown=ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key==='Enter'){ev.preventDefault();form.requestSubmit();}};void sync(channel);}}
 async function action(ev){const el=ev.target.closest('[data-chat-action]');if(!el||sending)return;if(el.dataset.chatAction==='select-group'){selectConversation('team');return;}if(el.dataset.chatAction==='select-person'){const p=people.find(p=>p.user_id===el.dataset.user);if(p?.user_id)selectConversation(directChannel(ctx().user.id,p.user_id));return;}const channel=el.closest('[data-chat-channel]')?.dataset.chatChannel;if(!channel)return;try{if(el.dataset.chatAction==='task'){onOpenTask(Number(el.dataset.id));return;}if(el.dataset.chatAction==='older')return await sync(channel,true);if(el.dataset.chatAction==='refresh')return await sync(channel);
 if(el.dataset.chatAction==='download'){const f=fileById(Number(el.dataset.file));if(!f)return;el.disabled=true;const url=await loadBlob(f),a=document.createElement('a');a.href=url;a.download=f.name;document.body.append(a);a.click();a.remove();el.disabled=false;}
 if(el.dataset.chatAction==='remove'){const m=cache.get(channel)?.messages.find(m=>m.id===Number(el.dataset.id));if(!m||(!ctx().state.viewer.manager&&m.author_id!==ctx().user.id)||!confirm('Bu mesaj ve ekleri konuşmadaki herkesten silinsin mi? Bu işlem geri alınamaz.'))return;const {error}=await client.rpc('sks_chat_remove',{p_id:Number(el.dataset.id)});if(error)throw error;if(m?.files?.length){const r=await client.storage.from(CHAT_BUCKET).remove(m.files.map(f=>f.path));if(r.error)notify('Mesaj kaldırıldı; dosyalar erişime kapatıldı ancak depolama temizliği tamamlanamadı.',true);}await sync(channel);}
 }catch(err){el.disabled=false;notify(err.message,true);}}
 document.addEventListener('click',action);
 function reset(){epoch++;viewerId=null;if(timer)clearInterval(timer);timer=null;if(subscription)client.removeChannel(subscription);subscription=null;cache.clear();people=[];peopleSearch='';homeChannel='team';unread=[];sending=false;for(const u of urls.values())URL.revokeObjectURL(u);urls.clear();onUnread([]);}
 function start(){const id=ctx().user?.id;if(!id||id===viewerId)return;reset();viewerId=id;active='team';void loadPeople();void sync('team');timer=setInterval(()=>{if(document.visibilityState==='visible'){void sync(panel(active)?active:panel(homeChannel)?homeChannel:'team');void loadPeople();}},10000);subscription=client.channel('sks-chat-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'sks_messages'},()=>void sync(panel(active)?active:panel(homeChannel)?homeChannel:'team')).on('postgres_changes',{event:'UPDATE',schema:'public',table:'sks_messages'},()=>void sync(panel(active)?active:panel(homeChannel)?homeChannel:'team')).subscribe();}
 document.addEventListener('visibilitychange',()=>{if(viewerId&&document.visibilityState==='visible')void sync(panel(active)?active:panel(homeChannel)?homeChannel:'team');});
 return {home,view,bind,start,reset,sync};
}
