"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { toPng } from "html-to-image";
import JSZip from "jszip";
import { Archive, ArrowRight, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Download, Image as ImageIcon, LayoutGrid, Mail, MapPin, Mic2, Plus, Sparkles, Trash2, Upload, UsersRound } from "lucide-react";

type Format = "mail" | "post" | "story" | "summary";
type EventItem = { id:string; club:string; title:string; date:string; time:string; speaker:string; campus:string; location:string; order?:number; logoOverride?:string };
const FORMATS:Record<Format,{label:string;size:string;w:number;h:number;icon:typeof Mail}>={
 mail:{label:"Mail Bülteni",size:"1200 × otomatik",w:1200,h:1680,icon:Mail},post:{label:"Instagram Post",size:"1080 × 1350",w:1080,h:1350,icon:ImageIcon},story:{label:"Instagram Story",size:"1080 × 1920",w:1080,h:1920,icon:Sparkles},summary:{label:"Haftalık Özet",size:"1080 × 1350",w:1080,h:1350,icon:LayoutGrid}
};
const CAMPUS:Record<string,{key:string;color:string;soft:string}>={merkez:{key:"Merkez",color:"#37478C",soft:"#E9ECF8"},güney:{key:"Güney",color:"#67B33F",soft:"#EDF7E8"},guney:{key:"Güney",color:"#67B33F",soft:"#EDF7E8"},çarşı:{key:"Çarşı",color:"#B5A52B",soft:"#F7F4DD"},carsi:{key:"Çarşı",color:"#B5A52B",soft:"#F7F4DD"},np:{key:"NP",color:"#24AAA7",soft:"#E5F7F6"}};
const SUMMARY_COLORS=[
 {color:"#24AAA7",soft:"#E5F7F6"},{color:"#67B33F",soft:"#EDF7E8"},{color:"#37478C",soft:"#E9ECF8"},
 {color:"#B5A52B",soft:"#F7F4DD"},{color:"#B41655",soft:"#F9E8EF"},{color:"#E2763E",soft:"#FCEDE5"},{color:"#7557B8",soft:"#F0ECFA"}
];
const FIXED_HOLIDAYS:Record<string,string>={
 "01-01":"Yılbaşı","04-23":"Ulusal Egemenlik ve Çocuk Bayramı","05-01":"Emek ve Dayanışma Günü","05-19":"Atatürk’ü Anma, Gençlik ve Spor Bayramı","07-15":"Demokrasi ve Millî Birlik Günü","08-30":"Zafer Bayramı","10-28":"Cumhuriyet Bayramı Arifesi · 13.00 sonrası","10-29":"Cumhuriyet Bayramı"
};
const DATED_HOLIDAYS:Record<string,string>={
 "2026-03-19":"Ramazan Bayramı Arifesi · 13.00 sonrası","2026-03-20":"Ramazan Bayramı · 1. Gün","2026-03-21":"Ramazan Bayramı · 2. Gün","2026-03-22":"Ramazan Bayramı · 3. Gün",
 "2026-05-26":"Kurban Bayramı Arifesi · 13.00 sonrası","2026-05-27":"Kurban Bayramı · 1. Gün","2026-05-28":"Kurban Bayramı · 2. Gün","2026-05-29":"Kurban Bayramı · 3. Gün","2026-05-30":"Kurban Bayramı · 4. Gün",
 "2027-03-08":"Ramazan Bayramı Arifesi · 13.00 sonrası","2027-03-09":"Ramazan Bayramı · 1. Gün","2027-03-10":"Ramazan Bayramı · 2. Gün","2027-03-11":"Ramazan Bayramı · 3. Gün",
 "2027-05-15":"Kurban Bayramı Arifesi · 13.00 sonrası","2027-05-16":"Kurban Bayramı · 1. Gün","2027-05-17":"Kurban Bayramı · 2. Gün","2027-05-18":"Kurban Bayramı · 3. Gün","2027-05-19":"Kurban Bayramı · 4. Gün"
};
const samples:EventItem[]=[
 {id:"1",club:"Sosyal Hizmet Kulübü",title:"Ekranın Arkasındaki Şiddet",date:"2026-09-21",time:"14.00–17.00",speaker:"Dr. Deniz Yalçın",campus:"Çarşı Yerleşkesi",location:"302 Nolu Derslik"},
 {id:"2",club:"Bilişim Kulübü",title:"Microsoft Teknoloji Gezisi",date:"2026-09-21",time:"13.00–14.00",speaker:"",campus:"Merkez Yerleşkesi",location:"Microsoft İstanbul"},
 {id:"3",club:"Sosyoloji Kulübü",title:"Toplumsal Açıdan Okullarda Şiddet",date:"2026-09-21",time:"12.00–13.00",speaker:"",campus:"Güney Yerleşkesi",location:"E Blok Bahçe"},
 {id:"4",club:"Tarih ve Kültür Kulübü",title:"Dijital ve Fiziki Tarih Söyleşileri",date:"2026-09-21",time:"15.00–16.00",speaker:"",campus:"Merkez Yerleşkesi",location:"Şehit Duha Beker Salonu"},
 {id:"5",club:"Dans Kulübü veya Müzik Kulübü",title:"Kampüste Ritim Buluşması",date:"2026-09-21",time:"18.00–20.00",speaker:"",campus:"NP Yerleşkesi",location:"Açık Etkinlik Alanı"},
 {id:"6",club:"Genç Gönüllüler Kulübü",title:"Gönüllülük Tanışma Toplantısı",date:"2026-09-21",time:"16.30–17.30",speaker:"",campus:"Çarşı Yerleşkesi",location:"Emir Nebi Konferans Salonu"},
 {id:"7",club:"Animasyon Kulübü",title:"Animasyon Atölyesi",date:"2026-09-22",time:"10.00–12.00",speaker:"",campus:"Merkez Yerleşkesi",location:"A Blok 201"},
 {id:"8",club:"Çocuk Gelişimi Kulübü",title:"Çocuklarla Yaratıcı Oyun",date:"2026-09-22",time:"13.00–14.30",speaker:"",campus:"Güney Yerleşkesi",location:"Beylerbeyi Salonu"},
 {id:"9",club:"Fizyoterapi Kulübü",title:"Sağlıklı Yaşam Buluşması",date:"2026-09-22",time:"15.00–16.30",speaker:"",campus:"NP Yerleşkesi",location:"Spor Salonu"},
 {id:"10",club:"Tiyatro Kulübü",title:"Sahneye İlk Adım",date:"2026-09-22",time:"17.00–19.00",speaker:"",campus:"Çarşı Yerleşkesi",location:"Ayhan Songar Salonu"},
 {id:"11",club:"Yapay Zekâ ve Akıllı Sistemler Kulübü",title:"Yapay Zekâya Giriş",date:"2026-09-23",time:"11.00–12.30",speaker:"",campus:"Merkez Yerleşkesi",location:"Nermin Tarhan Salonu"},
 {id:"12",club:"Çeviri Kulübü",title:"Diller Arası Kültür",date:"2026-09-23",time:"13.00–14.00",speaker:"",campus:"Güney Yerleşkesi",location:"E Blok 204"},
 {id:"13",club:"Kızılay Kulübü",title:"Afet Farkındalık Eğitimi",date:"2026-09-23",time:"14.30–16.00",speaker:"",campus:"Çarşı Yerleşkesi",location:"Kuleli Salonu"},
 {id:"14",club:"Sinema Kulübü",title:"Kısa Film Gösterimi",date:"2026-09-23",time:"18.00–20.00",speaker:"",campus:"Merkez Yerleşkesi",location:"Cep Sineması"},
 {id:"15",club:"Beslenme ve Diyetetik Kulübü",title:"Kampüste Sağlıklı Beslenme",date:"2026-09-24",time:"10.30–12.00",speaker:"",campus:"NP Yerleşkesi",location:"NP Sağlık Yerleşkesi"},
 {id:"16",club:"Hemşirelik Kulübü",title:"Sağlıkta İletişim",date:"2026-09-24",time:"13.00–14.30",speaker:"",campus:"NP Yerleşkesi",location:"Konferans Salonu"},
 {id:"17",club:"Genç Yeşilay Kulübü",title:"Bağımsız Yaşam Atölyesi",date:"2026-09-24",time:"15.00–16.00",speaker:"",campus:"Çarşı Yerleşkesi",location:"D Blok 101"},
 {id:"18",club:"Moleküler Biyoloji ve Genetik Kulübü",title:"Bilimsel Araştırma Buluşması",date:"2026-09-25",time:"11.00–12.30",speaker:"",campus:"Merkez Yerleşkesi",location:"Nermin Tarhan Salonu"},
 {id:"19",club:"Sürdürülebilir Kalkınma Kulübü",title:"Sürdürülebilir Kampüs",date:"2026-09-25",time:"14.00–15.30",speaker:"",campus:"Güney Yerleşkesi",location:"E Blok Bahçe"},
 {id:"20",club:"Tasarım Kulübü",title:"Afiş Tasarım Atölyesi",date:"2026-09-25",time:"16.00–18.00",speaker:"",campus:"Çarşı Yerleşkesi",location:"İletişim Atölyesi"}
];
const normalize=(v:string)=>v.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9]/g,"");
const pad=(n:number)=>String(n).padStart(2,"0");
const isoDate=(v:unknown)=>{if(!v)return"";if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return `${d.y}-${pad(d.m)}-${pad(d.d)}`}const d=new Date(String(v));return Number.isNaN(d.getTime())?String(v):`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const displayDate=(iso:string)=>new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${iso}T12:00:00`));
const dayName=(iso:string)=>new Intl.DateTimeFormat("tr-TR",{weekday:"long"}).format(new Date(`${iso}T12:00:00`));
const weekBounds=(iso:string)=>{const start=new Date(`${iso}T12:00:00`),day=(start.getDay()+6)%7;start.setDate(start.getDate()-day);const end=new Date(start);end.setDate(end.getDate()+6);const asIso=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;return{start:asIso(start),end:asIso(end)}};
const displayWeekRange=(iso:string)=>{const week=weekBounds(iso),first=displayDate(week.start).split(" ");return `${first.slice(0,-1).join(" ")} - ${displayDate(week.end)}`};
const getHoliday=(iso:string)=>{const labels=[DATED_HOLIDAYS[iso],FIXED_HOLIDAYS[iso.slice(5)]].filter(Boolean);return labels.join(" · ")};
const getCampus=(name:string)=>Object.entries(CAMPUS).find(([k])=>normalize(name).includes(normalize(k)))?.[1]??{key:"Diğer",color:"#B41655",soft:"#F9E8EF"};
// “ve” kulüp adının doğal bir parçası olabilir. Ortak kulüp yalnızca “veya”
// ya da açık ayraçlarla (&, +, virgül, noktalı virgül, /) belirtilir.
const splitClubs=(club:string)=>club.split(/\s+(?:veya|&|\+)\s+|\s*[,;/]\s*/i).filter(Boolean).slice(0,3);
const startTime=(time:string)=>{const m=time.match(/(\d{1,2})[.:](\d{2})/);return m?Number(m[1])*60+Number(m[2]):9999};

function ClubLogo({name,logos,small=false,override}:{name:string;logos:Record<string,string>;small?:boolean;override?:string}){if(override)return <img className={`club-logo ${small?"small":""}`} src={override} alt=""/>;const key=Object.keys(logos).find(k=>normalize(name).includes(k)||k.includes(normalize(name)));if(key)return <img className={`club-logo ${small?"small":""}`} src={logos[key]} alt=""/>;const initials=name.replace(/Üsküdar Üniversitesi/gi,"").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toLocaleUpperCase("tr-TR")||"SK";return <span className={`club-logo fallback ${small?"small":""}`}>{initials}</span>}

export default function Home(){
 const[format,setFormat]=useState<Format>("post"),[events,setEvents]=useState<EventItem[]>(samples),[selected,setSelected]=useState("1"),[logos,setLogos]=useState<Record<string,string>>({}),[background,setBackground]=useState("/arka-plan.png"),[scale,setScale]=useState(.48),[notice,setNotice]=useState("Kulüp logoları hazır"),[page,setPage]=useState(0),[quickOpen,setQuickOpen]=useState(false),[exporting,setExporting]=useState(false);
 const previewWrap=useRef<HTMLDivElement>(null),canvas=useRef<HTMLDivElement>(null),dragged=useRef<string|null>(null);
 const grouped=useMemo(()=>Object.entries(events.reduce<Record<string,EventItem[]>>((a,e)=>{(a[e.date]??=[]).push(e);return a},{})).sort(([a],[b])=>a.localeCompare(b)).map(([date,items])=>[date,items.sort((a,b)=>(a.order??startTime(a.time))-(b.order??startTime(b.time)))] as [string,EventItem[]]),[events]);
 const mailHeight=useMemo(()=>Math.max(1120,305+grouped.reduce((total,[,items])=>total+72+Math.ceil(items.length/4)*210,0)),[grouped]);
 const f=format==="mail"?{...FORMATS.mail,h:mailHeight}:FORMATS[format];
 const socialPages=useMemo(()=>{const pages:EventItem[][]=[];grouped.forEach(([,items])=>{for(let i=0;i<items.length;i+=4)pages.push(items.slice(i,i+4))});return pages.length?pages:[[]]},[grouped]);
 const visibleGrouped=useMemo(()=>{if(format!=="post"&&format!=="story")return grouped;return Object.entries((socialPages[Math.min(page,socialPages.length-1)]||[]).reduce<Record<string,EventItem[]>>((a,e)=>{(a[e.date]??=[]).push(e);return a},{})).sort(([a],[b])=>a.localeCompare(b))},[format,grouped,page,socialPages]);
 useEffect(()=>{setPage(0)},[format,events.length]);
 useEffect(()=>{const update=()=>{if(!previewWrap.current)return;const b=previewWrap.current.getBoundingClientRect();setScale(Math.min((b.width-64)/f.w,(b.height-64)/f.h,.72))};update();const o=new ResizeObserver(update);if(previewWrap.current)o.observe(previewWrap.current);return()=>o.disconnect()},[f.w,f.h]);
 useEffect(()=>{fetch("/logo-eslestirme-tablosu.csv").then(r=>r.text()).then(text=>{const builtins:Record<string,string>={};text.replace(/^\uFEFF/,"").split(/\r?\n/).slice(1).forEach(line=>{const comma=line.indexOf(",");if(comma<1)return;const file=line.slice(0,comma).trim(),name=line.slice(comma+1).trim();if(file&&name)builtins[normalize(name)]=`/logos/${file}`});setLogos(current=>({...builtins,...current}))}).catch(()=>setNotice("Logolar yüklenemedi; özel klasör seçilebilir"))},[]);
 const range=useMemo(()=>{const dates=events.map(e=>e.date).filter(Boolean).sort();if(!dates.length)return"HAFTA SEÇİLMEDİ";return `${displayDate(dates[0]).replace(/\s\d{4}$/,"")} – ${displayDate(dates.at(-1)!)}`.toLocaleUpperCase("tr-TR")},[events]);
 const rangeExact=useMemo(()=>{const anchor=events.map(e=>e.date).filter(Boolean).sort()[0];return anchor?displayWeekRange(anchor):"Tarih Aralığı Seçilmedi"},[events]);
 async function importExcel(file?:File){if(!file)return;const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true}),sheet=wb.Sheets["Tüm Etkinlikler"]??wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});const mapped=rows.map(r=>({id:crypto.randomUUID(),club:String(r["Kulüp Adı"]||"Kulüp belirtilmedi"),title:String(r["Etkinlik Adı"]||"Etkinlik"),date:isoDate(r["Tarih"]),time:r["Saat"] instanceof Date?`${pad((r["Saat"] as Date).getHours())}.${pad((r["Saat"] as Date).getMinutes())}`:String(r["Saat"]||""),speaker:String(r["Konuşmacılar"]||""),campus:String(r["Yerleşkesi"]||""),location:String(r["Etkinlik Yeri"]||r["Mekan"]||"")})).filter(e=>e.date||e.title);if(mapped.length){setEvents(mapped);setSelected(mapped[0].id);setNotice(`${mapped.length} etkinlik Excel’den aktarıldı`)}}
 function importLogos(files:FileList|null){if(!files)return;const next:Record<string,string>={};Array.from(files).forEach(file=>{next[normalize(file.name.replace(/\.[^.]+$/,"") )]=URL.createObjectURL(file)});setLogos(p=>({...p,...next}));setNotice(`${files.length} logo eşleştirmeye hazır`)}
 function update(id:string,key:keyof EventItem,value:string){setEvents(current=>{const old=current.find(e=>e.id===id);if(!old)return current;const nextDate=key==="date"?value:old.date,resetOrder=key==="date"||key==="time";return current.map(e=>{if(e.id===id)return{...e,[key]:value,order:resetOrder?undefined:e.order};if(resetOrder&&(e.date===old.date||e.date===nextDate))return{...e,order:undefined};return e})})}
 function addEvent(){const id=crypto.randomUUID();setEvents(v=>[...v,{id,club:"Yeni Kulüp",title:"Yeni Etkinlik",date:v.at(-1)?.date||"2026-09-21",time:"12.00–13.00",speaker:"",campus:"Merkez Yerleşkesi",location:""}]);setSelected(id)}
 function selectForEdit(id:string){setSelected(id);setQuickOpen(true)}
 function moveEvent(sourceId:string,targetId:string){if(sourceId===targetId)return;setEvents(current=>{const source=current.find(e=>e.id===sourceId),target=current.find(e=>e.id===targetId);if(!source||!target)return current;const moved=current.map(e=>e.id===sourceId?{...e,date:target.date}:e),day=moved.filter(e=>e.date===target.date).sort((a,b)=>(a.order??startTime(a.time))-(b.order??startTime(b.time))),without=day.filter(e=>e.id!==sourceId),targetIndex=Math.max(0,without.findIndex(e=>e.id===targetId)),ordered=[...without.slice(0,targetIndex),moved.find(e=>e.id===sourceId)!,...without.slice(targetIndex)];const ranks=new Map(ordered.map((e,i)=>[e.id,i]));return moved.map(e=>ranks.has(e.id)?{...e,order:ranks.get(e.id)}:e)});setNotice("Kart sırası güncellendi")}
 async function download(){if(!canvas.current)return;setNotice("PNG hazırlanıyor…");const data=await toPng(canvas.current,{cacheBust:true,pixelRatio:1,width:f.w,height:f.h,style:{transform:"none"}});const a=document.createElement("a"),suffix=(format==="post"||format==="story")?`-sayfa-${page+1}`:"";a.download=`sks-etkinlik-${format}${suffix}.png`;a.href=data;a.click();setNotice("Yüksek çözünürlüklü PNG indirildi")}
 async function downloadAll(){if(exporting)return;setExporting(true);setNotice("Tüm tasarımlar hazırlanıyor…");try{const zip=new JSZip(),nodes=Array.from(document.querySelectorAll<HTMLElement>("[data-export-name]"));for(let i=0;i<nodes.length;i++){const node=nodes[i],name=node.dataset.exportName||`tasarim-${i+1}.png`,w=Number(node.dataset.exportWidth),h=Number(node.dataset.exportHeight);setNotice(`${i+1} / ${nodes.length} tasarım hazırlanıyor…`);const data=await toPng(node,{cacheBust:true,pixelRatio:1,width:w,height:h,style:{transform:"none"}});zip.file(name,data.split(",")[1],{base64:true})}const blob=await zip.generateAsync({type:"blob",compression:"DEFLATE",compressionOptions:{level:6}}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="sks-etkinlik-tum-tasarimlar.zip";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`${nodes.length} tasarım ZIP olarak indirildi`)}catch{setNotice("Toplu indirme hazırlanamadı; yeniden deneyin")}finally{setExporting(false)}}
 const selectedEvent=events.find(e=>e.id===selected);
 return <main className="studio-shell">{quickOpen&&selectedEvent&&<QuickEditor event={selectedEvent} onClose={()=>setQuickOpen(false)} onUpdate={(key,value)=>update(selected,key,value)} onDelete={()=>{setEvents(v=>v.filter(e=>e.id!==selected));setQuickOpen(false)}}/>}<header className="topbar"><div className="brand-mark">SKS</div><div><h1>Etkinlik Stüdyosu</h1><p>2026–2027 Akademik Yılı</p></div><div className="top-actions"><span className="status"><i/> {notice}</span><button className="download secondary" disabled={exporting} onClick={downloadAll}><Archive size={18}/> {exporting?"Hazırlanıyor…":"Tümünü İndir"}</button><button className="download" disabled={exporting} onClick={download}><Download size={18}/> PNG İndir</button></div></header>
 <div className="workspace"><aside className="controls">
  <section className="control-section"><Title n="01" title="Çıktı formatı" sub="Tasarım türünü seç"/><div className="format-grid">{(Object.entries(FORMATS) as [Format,typeof f][]).map(([key,item])=>{const Icon=item.icon;return <button key={key} className={format===key?"active":""} onClick={()=>setFormat(key)}><Icon size={17}/><b>{item.label}</b><small>{item.size}</small></button>})}</div></section>
  <section className="control-section"><Title n="02" title="İçerik kaynakları" sub="Excel, logo ve arka plan"/><label className="upload-row"><span className="upload-icon excel"><Upload size={18}/></span><span><b>Excel’i içe aktar</b><small>SKS Etkinlik İstatistik şablonu</small></span><input type="file" accept=".xlsx,.xls" onChange={e=>importExcel(e.target.files?.[0])}/><ChevronDown size={17}/></label><label className="upload-row"><span className="upload-icon logos"><UsersRound size={18}/></span><span><b>Kulüp logoları klasörü</b><small>{Object.keys(logos).length?`${Object.keys(logos).length} logo yüklendi`:"Dosya adına göre otomatik eşleşir"}</small></span><input type="file" accept="image/*" multiple {...({webkitdirectory:""} as object)} onChange={e=>importLogos(e.target.files)}/><ChevronDown size={17}/></label><label className="upload-row"><span className="upload-icon bg"><ImageIcon size={18}/></span><span><b>Arka planı değiştir</b><small>JPG veya PNG · isteğe bağlı</small></span><input type="file" accept="image/*" onChange={e=>{const x=e.target.files?.[0];if(x)setBackground(URL.createObjectURL(x))}}/><ChevronDown size={17}/></label></section>
  <section className="control-section events-panel"><div className="section-title row"><span>03</span><div><b>Etkinlikler</b><small>{events.length} kayıt · alanlar düzenlenebilir</small></div><button className="icon-btn" onClick={addEvent}><Plus size={18}/></button></div><div className="event-list">{events.map(e=><button key={e.id} onClick={()=>setSelected(e.id)} className={`event-row ${selected===e.id?"active":""}`} style={{"--event-color":getCampus(e.campus).color} as React.CSSProperties}><div className="mini-logo"><ClubLogo name={e.club} logos={logos} small/></div><span><b>{e.title}</b><small>{e.club} · {e.time}</small></span><ChevronDown size={15}/></button>)}</div></section>
 </aside><section className="preview-area" ref={previewWrap}><div className="preview-toolbar"><div><b>Canlı önizleme</b><small>{f.label} · %{Math.round(scale*100)} ölçek</small></div>{(format==="post"||format==="story")&&<div className="page-nav"><button disabled={page===0} onClick={()=>setPage(p=>Math.max(0,p-1))}><ChevronLeft/></button><b>{page+1} / {socialPages.length}</b><button disabled={page>=socialPages.length-1} onClick={()=>setPage(p=>Math.min(socialPages.length-1,p+1))}><ChevronRight/></button></div>}<div className="legend">{[CAMPUS.merkez,CAMPUS.güney,CAMPUS.np,CAMPUS.çarşı].map(x=><span key={x.key}><i style={{background:x.color}}/>{x.key}</span>)}</div></div><div className="canvas-stage"><div className={`design-canvas ${format}`} ref={canvas} style={{width:f.w,height:f.h,transform:`scale(${scale})`,backgroundImage:background?`linear-gradient(180deg,rgba(5,40,29,.82),rgba(5,26,21,.94)),url(${background})`:undefined}}><DesignHeader range={(format==="post"||format==="story")&&socialPages[page]?.[0]?displayDate(socialPages[page][0].date):rangeExact} count={(format==="post"||format==="story")?socialPages[page]?.length||0:events.length}/>{format==="summary"?<SummaryGrid events={events} logos={logos}/>:<EventDesign grouped={visibleGrouped} logos={logos} format={format} onSelect={selectForEdit} onMove={moveEvent} dragged={dragged}/>}<DesignFooter/></div></div></section></div><BatchExports grouped={grouped} pages={socialPages} events={events} logos={logos} background={background} range={rangeExact} mailHeight={mailHeight}/></main>
}
function QuickEditor({event,onClose,onUpdate,onDelete}:{event:EventItem;onClose:()=>void;onUpdate:(key:keyof EventItem,value:string)=>void;onDelete:()=>void}){return <div className="quick-editor-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="quick-editor"><header><div><b>Etkinliği düzenle</b><small>Değişiklikler bütün tasarımlara uygulanır</small></div><button onClick={onClose}>×</button></header><div className="quick-fields"><label className="wide">Etkinlik adı<input value={event.title} onChange={e=>onUpdate("title",e.target.value)}/></label><label className="wide">Kulüp adı<input value={event.club} onChange={e=>onUpdate("club",e.target.value)}/></label><label>Tarih<input type="date" value={event.date} onChange={e=>onUpdate("date",e.target.value)}/></label><label>Saat<input value={event.time} onChange={e=>onUpdate("time",e.target.value)}/></label><label className="wide">Mekân<input value={event.location} onChange={e=>onUpdate("location",e.target.value)}/></label><label className="wide">Yerleşke<select value={event.campus} onChange={e=>onUpdate("campus",e.target.value)}><option>Merkez Yerleşkesi</option><option>Güney Yerleşkesi</option><option>Çarşı Yerleşkesi</option><option>NP Yerleşkesi</option></select></label><label className="logo-change wide"><span><b>Etkinlik logosu</b><small>Kulüp adına göre otomatik eşleşir veya özel logo yüklenebilir.</small></span><input type="file" accept="image/*" onChange={e=>{const file=e.target.files?.[0];if(file)onUpdate("logoOverride",URL.createObjectURL(file))}}/><em>{event.logoOverride?"Özel logo seçildi":"Logo değiştir"}</em></label></div><footer><button className="delete" onClick={onDelete}><Trash2 size={15}/> Etkinliği sil</button><button className="save" onClick={onClose}>Tamam</button></footer></section></div>}
function Title({n,title,sub}:{n:string;title:string;sub:string}){return <div className="section-title"><span>{n}</span><div><b>{title}</b><small>{sub}</small></div></div>}
function DesignHeader({range}:{range:string;count:number}){return <header className="design-header"><div className="header-brand-logo"><img src="/logos/uulogo-cropped.png" alt="Üsküdar Üniversitesi"/></div><div className="header-copy"><small>Sağlık, Kültür ve Spor Daire Başkanlığı</small><strong>{range}</strong><b>Öğrenci Kulübü Etkinlikleri</b></div><div className="header-brand-logo right"><img src="/logos/skslogo.png" alt="SKS"/></div></header>}
function LogoGroup({club,logos,override}:{club:string;logos:Record<string,string>;override?:string}){const clubs=splitClubs(club);return <div className={`logo-group count-${override?1:clubs.length}`}>{override?<ClubLogo name={club} logos={logos} override={override}/>:clubs.map((c,i)=><ClubLogo key={i} name={c} logos={logos}/>)}</div>}
function EventCard({event,logos,onSelect,onMove,dragged}:{event:EventItem;logos:Record<string,string>;onSelect:(id:string)=>void;onMove:(source:string,target:string)=>void;dragged:React.MutableRefObject<string|null>}){const c=getCampus(event.campus);return <article className="design-card interactive" draggable onDragStart={()=>{dragged.current=event.id}} onDragEnd={()=>{dragged.current=null}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragged.current)onMove(dragged.current,event.id)}} onClick={()=>onSelect(event.id)} title="Düzenlemek için tıklayın; sıralamak için sürükleyin" style={{"--c":c.color,"--soft":c.soft} as React.CSSProperties}><div className="card-head"><LogoGroup club={event.club} logos={logos} override={event.logoOverride}/><span>{event.club}</span></div><h3>{event.title}</h3><div className="time">{event.time}</div><div className="meta"><span><MapPin/> {event.location||"Mekân bilgisi eklenecek"}</span><span className="campus">{c.key} Yerleşkesi</span></div></article>}
function EventDesign({grouped,logos,format,onSelect,onMove,dragged}:{grouped:[string,EventItem[]][];logos:Record<string,string>;format:Format;onSelect:(id:string)=>void;onMove:(source:string,target:string)=>void;dragged:React.MutableRefObject<string|null>}){return <div className="design-body">{grouped.map(([date,items],dayIndex)=>{const rows:EventItem[][]=[];if(format==="mail"){for(let i=0;i<items.length;i+=4)rows.push(items.slice(i,i+4))}else rows.push(items);const dayColor=format==="mail"?SUMMARY_COLORS[dayIndex%SUMMARY_COLORS.length].color:getCampus(items[0]?.campus||"").color;return <section className="day-section" key={date}><div className="day-label" style={{background:dayColor}}><b>{displayDate(date)}</b><span>{dayName(date)}</span></div>{rows.map((row,i)=><div className={`cards-grid ${format==="mail"?"mail-row ":""}cols-${row.length}`} key={i}>{row.map(e=><EventCard key={e.id} event={e} logos={logos} onSelect={onSelect} onMove={onMove} dragged={dragged}/>)}</div>)}</section>})}</div>}
function SummaryGrid({events,logos}:{events:EventItem[];logos:Record<string,string>}){const anchor=events.map(x=>x.date).filter(Boolean).sort()[0]||"2026-09-21",monday=weekBounds(anchor).start,days=Array.from({length:7},(_,i)=>{const x=new Date(`${monday}T12:00:00`);x.setDate(x.getDate()+i);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`});return <div className="summary-grid">{days.map((date,i)=>{const es=events.filter(e=>e.date===date),c=SUMMARY_COLORS[i%SUMMARY_COLORS.length],holiday=getHoliday(date),clubs=es.slice(0,10).flatMap(e=>e.logoOverride?[{name:e.club,override:e.logoOverride}]:splitClubs(e.club).map(name=>({name}))).slice(0,10);return <article key={date} className={holiday?"holiday-day":""} style={{"--c":c.color,"--soft":c.soft} as React.CSSProperties}><div className="summary-date"><span>{dayName(date).slice(0,3)}</span><b>{new Date(`${date}T12:00:00`).getDate()}</b></div>{holiday&&<div className="holiday-badge"><span>Resmî Tatil</span><b>{holiday}</b></div>}<div className={`summary-logos count-${clubs.length}`}>{clubs.map((club,j)=><ClubLogo key={j} name={club.name} logos={logos} override={club.override}/>)}</div></article>})}<div className="summary-note"><img src="/logos/skslogo.png" alt="SKS"/><b>Öğrenci kulübü etkinliklerinin detaylarını görüntülemek için kaydırın</b><ArrowRight aria-hidden="true"/></div></div>}
function DesignFooter(){return <footer className="design-footer"><div className="footer-info"><span>Detaylı bilgi için:</span><b>sks.uskudar.edu.tr</b></div><div className="footer-center"><img src="/logos/uulogo-cropped.png" alt="Üsküdar Üniversitesi"/><img src="/logos/skslogo.png" alt="SKS"/><strong>T.C. ÜSKÜDAR ÜNİVERSİTESİ<br/>SAĞLIK, KÜLTÜR VE SPOR<br/>DAİRE BAŞKANLIĞI</strong></div><div className="footer-social"><div><b>f</b><b>◎</b><b>in</b><b>▶</b><b>𝕏</b></div><span>@uskudarsks</span></div></footer>}

function BatchExports({grouped,pages,events,logos,background,range,mailHeight}:{grouped:[string,EventItem[]][];pages:EventItem[][];events:EventItem[];logos:Record<string,string>;background:string;range:string;mailHeight:number}){
 const batchDragged=useRef<string|null>(null),noop=()=>{};
 const bg=background?`linear-gradient(180deg,rgba(5,40,29,.82),rgba(5,26,21,.94)),url(${background})`:undefined;
 const pageGroups=(items:EventItem[])=>Object.entries(items.reduce<Record<string,EventItem[]>>((a,e)=>{(a[e.date]??=[]).push(e);return a},{})).sort(([a],[b])=>a.localeCompare(b)) as [string,EventItem[]][];
 return <div className="batch-exports" aria-hidden="true">
  <div className="design-canvas mail" data-export-name="01-mail-bulteni.png" data-export-width="1200" data-export-height={mailHeight} style={{width:1200,height:mailHeight,backgroundImage:bg}}><DesignHeader range={range} count={events.length}/><EventDesign grouped={grouped} logos={logos} format="mail" onSelect={noop} onMove={noop} dragged={batchDragged}/><DesignFooter/></div>
  {pages.map((items,i)=><div key={`post-${i}`} className="design-canvas post" data-export-name={`02-post-sayfa-${i+1}.png`} data-export-width="1080" data-export-height="1350" style={{width:1080,height:1350,backgroundImage:bg}}><DesignHeader range={items[0]?displayDate(items[0].date):range} count={items.length}/><EventDesign grouped={pageGroups(items)} logos={logos} format="post" onSelect={noop} onMove={noop} dragged={batchDragged}/><DesignFooter/></div>)}
  {pages.map((items,i)=><div key={`story-${i}`} className="design-canvas story" data-export-name={`03-story-sayfa-${i+1}.png`} data-export-width="1080" data-export-height="1920" style={{width:1080,height:1920,backgroundImage:bg}}><DesignHeader range={items[0]?displayDate(items[0].date):range} count={items.length}/><EventDesign grouped={pageGroups(items)} logos={logos} format="story" onSelect={noop} onMove={noop} dragged={batchDragged}/><DesignFooter/></div>)}
  <div className="design-canvas summary" data-export-name="04-haftalik-ozet.png" data-export-width="1080" data-export-height="1350" style={{width:1080,height:1350,backgroundImage:bg}}><DesignHeader range={range} count={events.length}/><SummaryGrid events={events} logos={logos}/><DesignFooter/></div>
 </div>
}
